
test-weibo_alk20:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20/

online-weibo_alk20:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20/

####################################################
test-weibo_alk_admin:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin/

online-weibo_alk_admin:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin/

#####################################################
test-weibo_alk20_dev:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev/

online-weibo_alk20_dev:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev/

#####################################################
test-weibo_alk20_dev3:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev3/

online-weibo_alk20_dev3:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev3/

#####################################################
test-weibo_alk20_dev4:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev4/

online-weibo_alk20_dev4:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_dev4/

#####################################################
test-weibo_alk20_test3:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_test3/

online-weibo_alk20_test3:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk20_test3/

######################################################
test-weibo_alk20_test4:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
		-m all_vic_sina_com_cn_test \
		-h dist.grid.sina.com.cn \
		-u channel02 weibo_alk20_test4/

online-weibo_alk20_test4:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
		-m all_vic_sina_com_cn \
		-h dist.grid.sina.com.cn \
		-u channel02 weibo_alk20_test4/

######################################################
test-weibo_alk_admin_dev:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin_dev/

online-weibo_alk_admin_dev:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin_dev/

######################################################
test-weibo_alk_admin_test:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin_test/

online-weibo_alk_admin_test:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk_admin_test/

######################################################
test-advertorial:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 advertorial/

online-advertorial:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 advertorial/

######################################################
test-weibo_alk:
	$(shell pwd)/bin/distrsync3 -f $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn_test \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk/

online-weibo_alk:
	$(shell pwd)/bin/distrsync3 -f  $(shell pwd)/conf/rsync.secrits \
                -m all_vic_sina_com_cn \
                -h dist.grid.sina.com.cn \
                -u channel02 weibo_alk/

